In [2]:
# Analytics
#1. Numpy - Mathematical operation with the array
#2. Pandas - Data Cleaning, Data insights , data manipulation
#3. Matplotlib - Visualization
#4. Seaborn - Advance visualization , Statical Analysis

# Numpy

In [4]:
di = [10,20,30]
ti = [5,10,15]

sp = di/ti

print(sp)


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
print(di+ti)

[10, 20, 30, 5, 10, 15]


In [7]:
a = '10'

print(a)
a

10


'10'

In [ ]:
dv

In [1]:
import numpy as np

In [10]:
d = numpy.array(di)
t = numpy.array(ti)

In [15]:

print(d)
t

[10 20 30]


array([ 5, 10, 15])

In [16]:
sp=d/t
sp

array([2., 2., 2.])

In [17]:
# Numpy Stands for Numerical python. It is a python foundational library that is used to peform mathematical operaion , linear algbirc function with the array.
# Numpy consists 2 things that is 1. array , 2. matrix

In [ ]:
# list Vs array

# list - list are my mutable data type that stores the elements comma seperatedly
    # - we can't perform mathematical operations in the list



# array - Array it is a methd in python library numpy that stores the numerical data type
        # - we can perform mathematical operation in array



# propties of array
- ndim
- shape
- size
- dtype

In [36]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [41]:
b=np.array([[1,2,3,4,5]])
print(b,type(b))
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3 4 5]] <class 'numpy.ndarray'>
2
(1, 5)
5


In [45]:
c=np.array([[1,2,3],[5,6,7],[7,8,9]])
print(c,type(c))
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[[1 2 3]
 [5 6 7]
 [7 8 9]] <class 'numpy.ndarray'>
2
(3, 3)
9
int32


In [42]:
x=np.array([[1],[3],[4]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[1]
 [3]
 [4]]
2
(3, 1)
3


In [43]:
d=np.array([[[[1,2,3],[5,6,7],[7,8,9]]]])
print(d,type(d))
print(d.ndim)
print(d.shape)
print(d.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]]]] <class 'numpy.ndarray'>
4
(1, 1, 3, 3)
9


In [47]:
e=np.array([[[[1,2,3],[5,6,72],[7.1,8,9],[7,8,9],[1,1,1]]]])
print(e,type(e))
print(e.ndim)
print(e.shape)
print(e.size)
print(e.dtype)

[[[[ 1.   2.   3. ]
   [ 5.   6.  72. ]
   [ 7.1  8.   9. ]
   [ 7.   8.   9. ]
   [ 1.   1.   1. ]]]] <class 'numpy.ndarray'>
4
(1, 1, 5, 3)
15
float64


In [50]:
# z = np.array([[1,2,3],[4,5],[6,7,8]])
# print(z)

# Indexing & Slicing

In [55]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[ 1  2  3  4  5  6 -7  8  9]]]


In [64]:
# print(a[0][0][0])
# print(a[0][0][1])
# print(a[0][0][0])
# print(a[0][0][-3])
# print(a[-1][-1][-3])
print(a[0][-1][3])

4


In [65]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,3]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12  3]]


In [73]:
# print(c[0])
# print(c[0][0])
# print(c[-1][-2])
# print(c[-1][1])
# print(c[-4][-2])
# print(c[2][-2])


In [77]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,3]]]])
print(d)
# print(d.shape)
# print(d.size)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [11 12  3]]]]


In [81]:
print(d[0][0][0])
print(d[0][0][-1][-3])

[1 2 3]
11


In [88]:
L=[1,2,3] # shallow copy
l=L

In [90]:
print(L,id(L))
print(l,id(l))

[1, 2, 3] 2776957711680
[1, 2, 3] 2776957711680


In [85]:
l.clear()

In [87]:
print(l)
print(L)

[]
[]


In [97]:
a=[1,2,3] # Deep copy
b=a.copy()

In [93]:
print(a,id(a))
print(b,id(b))

[1, 2, 3] 2776957855744
[1, 2, 3] 2776957864064


In [96]:
b.clear()
print(b)
print(a)

[]
[1, 2, 3]



disaply all the even number in the given rangge 1000 - 3000 where each and every digit is divibly by 2

# Slicing

In [2]:
f=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [8]:
# print(f[0][0][rows,columns])
# print(f[0][0][1:3 , 2:4])
# print(f[0][0][1:3,1:4])
# print(f[0][0][-4:-3,-4:-3])
# print(f[-1][-1][-1:,-1:])
# print(f[-1][-1][-1:,:-1])
# print(f[-1][0][-2:,2:100])
# print(f[0][0][1:4,-4:-1])
# print(f[0][-1][-3:-2,0:4])
# print(f[0][0][::-1,::-1])

# Shape Manipulation

In [12]:
a = np.array([[1,2,3],[5,6,7],[1,1,1],[0,6,3]])
print(a)
print(a.shape)
print(a.size)

[[1 2 3]
 [5 6 7]
 [1 1 1]
 [0 6 3]]
(4, 3)
12


In [20]:
# a.reshape(3,6)

In [21]:
np.transpose(a)

array([[1, 5, 1, 0],
       [2, 6, 1, 6],
       [3, 7, 1, 3]])

In [24]:
a.T

array([[1, 5, 1, 0],
       [2, 6, 1, 6],
       [3, 7, 1, 3]])

# Broadcasting

In [25]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])

In [28]:
print(arr1+arr2)
print(arr1+1)

[ 70  90 110 130 150]
[11 21 31 41 51]


In [29]:
b = np.array([[1,2,3],[4,5,6],[1,2,1]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 1]])

In [30]:
np.sum(b)

25

In [33]:
print(np.sum(b,axis=0))# here axis = 0 means rows
print(np.sum(b,axis=1)) # here axis =1 means cols

[ 6  9 10]
[ 6 15  4]


In [4]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [6]:
print(f[0][0][1:4,-3:-5])

[]


In [13]:
a = np.array([[[1,2,3],[1,1,1]]])
b = np.array([[1,1,1],[3,2,1]])

In [14]:
print(a,type(a))

[[[1 2 3]
  [1 1 1]]] <class 'numpy.ndarray'>


In [17]:
print(a*b)

[[[1 2 3]
  [3 2 1]]]


In [16]:
x = np.mat([[1,2,3],[1,1,1]])
y = np.mat([[1,1,1],[3,2,1]])

In [12]:
print(x,type(x))

[[1 2 3]
 [1 1 1]] <class 'numpy.matrix'>


In [19]:
print(y)

[[1 1 1]
 [3 2 1]]


In [22]:
y=y.T
y

matrix([[1, 3],
        [1, 2],
        [1, 1]])

In [23]:
print(x.shape,y.shape)

(2, 3) (3, 2)


In [24]:
print(x*y)

[[ 6 10]
 [ 3  6]]


In [26]:
a = np.fromfunction(lambda i,j : i+j,(2,2),dtype=int)
a

array([[0, 1],
       [1, 2]])

In [27]:
a = np.fromfunction(lambda i,j : i>j,(2,2),dtype=int)
a

array([[False, False],
       [ True, False]])

In [30]:
i = np.array([[1,2,3],[4,5,6]],ndmin=6)
print(i)
print(i.ndim)

[[[[[[1 2 3]
     [4 5 6]]]]]]
6


In [31]:
np.ravel(i)

array([1, 2, 3, 4, 5, 6])

In [34]:
i.flatten()

array([1, 2, 3, 4, 5, 6])

In [35]:
i

array([[[[[[1, 2, 3],
           [4, 5, 6]]]]]])

In [ ]:
# array creation

In [37]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
np.full((5,5),55)

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [63]:
a = np.ones((5,5),dtype=int)
a[1:4,1:4]=b
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [61]:
b=np.zeros((3,3),dtype=int)
b[1,1] = 9
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [64]:
L=[]
for i in range(1,26):
    a=int(input(f'enter element no. {i}'))
    L.append(a)
    

enter element no. 1 1
enter element no. 2 1
enter element no. 3 1
enter element no. 4 1
enter element no. 5 1
enter element no. 6 0
enter element no. 7 0
enter element no. 8 0
enter element no. 9 1
enter element no. 10 1
enter element no. 11 0
enter element no. 12 9
enter element no. 13 0
enter element no. 14 1
enter element no. 15 1
enter element no. 16 0
enter element no. 17 0
enter element no. 18 0
enter element no. 19 1
enter element no. 20 1
enter element no. 21 1
enter element no. 22 1
enter element no. 23 1
enter element no. 24 1
enter element no. 25 1


In [66]:
np.array(L,ndmin=2).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 9, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [71]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [97]:
np.random.randint(1,7)

2

In [117]:
np.random.randint(1,10,3)

array([8, 8, 8])

In [165]:
comp = np.random.randint(1,10)
chance = int(input('enter chances '))
print(comp)
while chance>0:

    user = int(input('guess the number '))
    
    if user==comp:
        print('guessed')
        break
    else:
        print('lost')
    chance-=1


enter chances  3


8


guess the number  8


guessed


In [242]:
L=['stone','paper','scissor']
u_score = 0
c_score=0
chance = int(input('enter chance '))
while chance !=0:
    
    comp = np.random.choice(L)
    user = input('play the game ')
    
    
    if comp==user:
        print('Tie')
    
    elif comp=='stone':
        if user=='paper':
            print('user wins')
            u_score +=1

        else:
            print('comp wins')
            c_score +=1

    
    elif comp=='paper':
        if user=='scissor':
            print('user wins')
            u_score +=1

        else:
            print('comp wins')
            c_score +=1

    
    else:
        if user=='stone':
            print('user wins')
            u_score +=1

        else:
            print('comp wins')
            c_score +=1

    chance-=1


if c_score==u_score:
    print('No wins')

elif c_score>u_score:
    print('Comp wins by',c_score)
else:
    print('user wins by',u_score)




        
        


enter chance  5
play the game  paper


user wins


play the game  paper


comp wins


play the game  stone


user wins


play the game  paper


Tie


play the game  scissor


comp wins
No wins


In [ ]:
shape
indexcing & slixcing
sum axis =0 , axis=1

In [49]:
# help(np)

In [52]:
# dir(np)