In [2]:
# Analytics
#1. Numpy - Mathematical operation with the array
#2. Pandas - Data Cleaning, Data insights , data manipulation
#3. Matplotlib - Visualization
#4. Seaborn - Advance visualization , Statical Analysis

# Numpy

In [4]:
di = [10,20,30]
ti = [5,10,15]

sp = di/ti

print(sp)


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
print(di+ti)

[10, 20, 30, 5, 10, 15]


In [7]:
a = '10'

print(a)
a

10


'10'

In [ ]:
dv

In [1]:
import numpy as np

In [10]:
d = numpy.array(di)
t = numpy.array(ti)

In [15]:

print(d)
t

[10 20 30]


array([ 5, 10, 15])

In [16]:
sp=d/t
sp

array([2., 2., 2.])

In [17]:
# Numpy Stands for Numerical python. It is a python foundational library that is used to peform mathematical operaion , linear algbirc function with the array.
# Numpy consists 2 things that is 1. array , 2. matrix

In [ ]:
# list Vs array

# list - list are my mutable data type that stores the elements comma seperatedly
    # - we can't perform mathematical operations in the list



# array - Array it is a methd in python library numpy that stores the numerical data type
        # - we can perform mathematical operation in array



# propties of array
- ndim
- shape
- size
- dtype

In [36]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [41]:
b=np.array([[1,2,3,4,5]])
print(b,type(b))
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3 4 5]] <class 'numpy.ndarray'>
2
(1, 5)
5


In [45]:
c=np.array([[1,2,3],[5,6,7],[7,8,9]])
print(c,type(c))
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[[1 2 3]
 [5 6 7]
 [7 8 9]] <class 'numpy.ndarray'>
2
(3, 3)
9
int32


In [42]:
x=np.array([[1],[3],[4]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[1]
 [3]
 [4]]
2
(3, 1)
3


In [43]:
d=np.array([[[[1,2,3],[5,6,7],[7,8,9]]]])
print(d,type(d))
print(d.ndim)
print(d.shape)
print(d.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]]]] <class 'numpy.ndarray'>
4
(1, 1, 3, 3)
9


In [47]:
e=np.array([[[[1,2,3],[5,6,72],[7.1,8,9],[7,8,9],[1,1,1]]]])
print(e,type(e))
print(e.ndim)
print(e.shape)
print(e.size)
print(e.dtype)

[[[[ 1.   2.   3. ]
   [ 5.   6.  72. ]
   [ 7.1  8.   9. ]
   [ 7.   8.   9. ]
   [ 1.   1.   1. ]]]] <class 'numpy.ndarray'>
4
(1, 1, 5, 3)
15
float64


In [50]:
# z = np.array([[1,2,3],[4,5],[6,7,8]])
# print(z)

# Indexing & Slicing

In [55]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[ 1  2  3  4  5  6 -7  8  9]]]


In [64]:
# print(a[0][0][0])
# print(a[0][0][1])
# print(a[0][0][0])
# print(a[0][0][-3])
# print(a[-1][-1][-3])
print(a[0][-1][3])

4


In [65]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,3]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12  3]]


In [73]:
# print(c[0])
# print(c[0][0])
# print(c[-1][-2])
# print(c[-1][1])
# print(c[-4][-2])
# print(c[2][-2])


In [77]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,3]]]])
print(d)
# print(d.shape)
# print(d.size)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [11 12  3]]]]


In [81]:
print(d[0][0][0])
print(d[0][0][-1][-3])

[1 2 3]
11


In [88]:
L=[1,2,3] # shallow copy
l=L

In [90]:
print(L,id(L))
print(l,id(l))

[1, 2, 3] 2776957711680
[1, 2, 3] 2776957711680


In [85]:
l.clear()

In [87]:
print(l)
print(L)

[]
[]


In [97]:
a=[1,2,3] # Deep copy
b=a.copy()

In [93]:
print(a,id(a))
print(b,id(b))

[1, 2, 3] 2776957855744
[1, 2, 3] 2776957864064


In [96]:
b.clear()
print(b)
print(a)

[]
[1, 2, 3]



disaply all the even number in the given rangge 1000 - 3000 where each and every digit is divibly by 2